# Generated by Django 2.2.2 on 2019-07-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
                ('Discription', models.CharField(max_length=1000)),
                ('Picture', models.CharField(max_length=500)),
                ('Active', models.BooleanField()),
                ('Created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField()),
                ('DOB', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('ProfileImg', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(max_length=100)),
                ('Allowed', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='shippers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDes', models.CharField(max_length=1000)),
                ('SupplierId', models.IntegerField()),
                ('QuantityPerUnit', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('MSRP', models.IntegerField()),
                ('AvilSize', models.CharField(max_length=100)),
                ('AvilColor', models.CharField(max_length=100)),
                ('Size', models.IntegerField()),
                ('Colour', models.CharField(max_length=100)),
                ('UnitWeight', models.IntegerField()),
                ('UnitInStock', models.IntegerField()),
                ('UnitOnOrder', models.IntegerField()),
                ('ProductAvil', models.BooleanField()),
                ('DiscountAvil', models.BooleanField()),
                ('picture', models.CharField(max_length=500)),
                ('Ranking', models.IntegerField()),
                ('Note', models.CharField(max_length=1000)),
                ('Discount', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.IntegerField()),
                ('OrderDate', models.CharField(max_length=100)),
                ('ShipDate', models.CharField(max_length=100)),
                ('RequiredDate', models.CharField(max_length=100)),
                ('ShipperId', models.IntegerField()),
                ('Freight', models.CharField(max_length=100)),
                ('TimeStamp', models.CharField(max_length=100)),
                ('TransactionsStatus', models.BooleanField()),
                ('ErrorMsg', models.CharField(max_length=500)),
                ('Fullfilled', models.CharField(max_length=100)),
                ('Deleted', models.BooleanField()),
                ('Paid', models.BooleanField()),
                ('PaymentDate', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.customers')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Qantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Size', models.CharField(max_length=100)),
                ('Colour', models.CharField(max_length=100)),
                ('Fullfilled', models.CharField(max_length=100)),
                ('ShipDate', models.CharField(max_length=100)),
                ('OrderDetailId', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.products')),
            ],
        ),
    ]
